management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: aistore-user

  cloud:
    nacos:
      discovery:
        server-addr: nacos
  datasource:
    url: jdbc:mysql://mysql:3306/user?useSSL=false
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: validate
