spring:
  redis:
    host: localhost
    port: 6380
  datasource:
    #    url: jdbc:mysql://localhost:3306/uams?useSSL=false
    url: jdbc:p6spy:mysql://localhost:3306/uams?useSSL=false
    username: root
    password:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update #// create-drop

saas:
  gateway:
    url: http://localhost:8080/