---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    usage: vluee-application
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata': {}
  name: spring-cloud-cm
  namespace: default

data:
  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always

  spring:
    cloud:
      nacos:
        discovery:
          server-addr: default.nacos:8848

        config:
          server-addr: default.nacos:8848
          file-extension: properties

  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
