spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      bindings:
        domain_events_input:
          destination: vluee_cloud_domain_events
          contentType: text/plain
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop