spring:
  redis:
    host: localhost
    port: 6380

  security:
    oauth2:
      resourceserver:
        jwt:
          # jwk-set-uri: http://localhost:8082/rsa/publicKey
          jwk-set-uri: http://localhost/rsa/publicKey


secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/v3/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/auth/token/**"
      - "/user/me"
      - "/sample/**"
      - "/saas-demo/**"
      - "/saas-users/users"
      - "/saas-gateway/**"
      # - "/saas-uams/**"
      - "/resources/**"
      - "/saas-auth/**"
      - "/saas-tenants/**"

logging:
  level:
    org.springframework.security: DEBUG
    com.vluee.cloud.gateway: DEBUG