spring:
  redis:
    host: localhost
    port: 6379

  kafka:
    producer:
      bootstrap-servers:
        - local_kafka:9092

    consumer:
      bootstrap-servers:
        - local_kafka:9092
      group-id: rule-reader-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/rsa/publicKey


secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/user/me"
      - "/sample/**"
      - "/saas-users/users"

logging:
  level:
    org.springframework.security: DEBUG
    com.vluee.cloud.gateway: DEBUG