spring:
  influx:
    url: http://localhost:8086
  datasource:
    url: jdbc:mysql://localhost:3306/tenants?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
kafka:
  broker:
    list: localhost:9092
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop