spring:
  influx:
    url: http://localhost:8086
  datasource:
    url: jdbc:mysql://localhost:3306/statistics?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      group-id: vc-statistics
      consumer-id: vs-statistics-idea
      client-id: h22222
  cloud:
    stream:
      default:
        group: 'hello'
      bindings:
        input:
          destination: cloud-domain-events
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create-drop