server:
  port: 9502
spring:
  application:
    name: aistore-monitor
  security:
    user:
      name: jzboss
      password: jzboss123
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server.endpoint}
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}