spring:
  datasource:
    url: ${auth.server.db.url}
    username: ${auth.server.db.username}
    password: ${auth.server.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: 'validate'