version: "3"
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - ./influxdb/conf:/etc/influxdb
      - ./influxdb/data:/var/lib/influxdb/data
      - ./influxdb/meta:/var/lib/influxdb/meta
      - ./influxdb/wal:/var/lib/influxdb/wal
    environment:
      - appendonly=yes
    ports:
      - "8083:8083"
      - "8086:8086"
    networks:
      - as-dev-swarm

networks:
  as-dev-swarm:
    external: true      