version: '3.1'

services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.8.34.143 # IP记得更新这个IP 否则会报错
      KAFKA_CREATE_TOPICS: "heyjue-test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo1:2182,zoo1:2183
      JMX_PORT: 1099
    networks:
      - as-dev-swarm
  # docker run -itd --name=kafka-manager -p 9000:9000 -e ZK_HOSTS="192.168.220.150:2181" sheepkiller/kafka-manager
  kafka_manager:
    image: kafkamanager/kafka-manager
    depends_on:
      - kafka
    ports:
      - "9093:9000"
    networks:
      - as-dev-swarm
    environment:
      ZK_HOSTS: zoo1:2181,zoo1:2182,zoo1:2183

networks:
  as-dev-swarm:
    external: true