spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orgs?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: 'create-drop'