spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orgs?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: 'create-drop'

  kafka:
    consumer:
      group-id: vc-orgs
  cloud:
    stream:
      bindings:
        vluee-cloud-pigu:
          destination: cloud-domain-events    #消息发往的目的地
          content-type: application/json